window.producerList = [
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "einstein",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "tesla",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "oppenheimer",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "campbell",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "hawking",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "plato",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://steemit-production-imageproxy-thumbnail.s3.amazonaws.com/DQmRDRboYHzeYvNrC1R5TUey2mfNs6rQHNJoPtxtxKxqUm5_128x128",
    "producer": "aristotle",
    "name": "EOS Nation",
    "contact": "EOS Nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "suntzu",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "descartes",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "socrates",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "neitzche",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "aquinas",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "locke",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "marx",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "443",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "kant",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "sartre",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "epicurus",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "kierkegaard",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "rand",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "hypatia",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://raw.githubusercontent.com/bystake/bystake-ui/master/bystake-crop.jpg",
    "producer": "edison",
    "name": "ByStake",
    "contact": "ByStake",
    "block": "",
    "URL": "52.80.130.81",
    "HTTP": "9989",
    "P2P": "9999",
    "Time": "",
    "API_URL": "http://52.80.130.81:9989"
  }
];
