window.producerList = [
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "einstein",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "tesla",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "oppenheimer",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "campbell",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "hawking",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "plato",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "aristotle",
    "name": "EOS nation",
    "contact": "EOS nation",
    "block": "",
    "URL": "testnet.eosnation.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosnation.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "suntzu",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "descartes",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "socrates",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "neitzche",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "aquinas",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "locke",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "marx",
    "name": "EOSoCal",
    "contact": "EOSoCal",
    "block": "",
    "URL": "testnet.eosocal.io",
    "HTTP": "80",
    "P2P": "9876",
    "Time": "",
    "API_URL": "https://testnet.eosocal.io"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "kant",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "sartre",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "epicurus",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "kierkegaard",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "rand",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "hypatia",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  },
  {
    "logo": "https://meet.one/assets/MEET.svg",
    "producer": "edison",
    "name": "MeetOne",
    "contact": "MeetOne",
    "block": "",
    "URL": "testnet.meet.one",
    "HTTP": "8888",
    "P2P": "9876",
    "Time": "",
    "API_URL": "http://testnet.meet.one:8888"
  }
];